# Generated by Django 5.0.2 on 2024-02-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='applicayion_date',
            new_name='application_date',
        ),
    ]
