# Generated by Django 5.0.2 on 2024-02-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_options_remove_exam_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
